from .categoriaCreateView import CategoriaCreateView
from .productoCreateView import  ProductoCreateView
from .usuariosCreateView import UsuariosCreateView
from .clienteCreateView import ClienteCreateView
from .ventasCreateView import VentasCreateView